### ISSUE TITLE
Melhorar itens.

### ISSUE THREAD

**Issue by emerson3** [Davison17/Apresentacao#1]
Colocar ícones melhores do github e do linkedin, aqueles estão feios para o fundo do site.
![image](https://user-images.githubusercontent.com/41524533/193968814-2042e632-2283-4c6f-8b4e-f219d7d5776d.png)

**Comment by Davison17** [comment]
![image](https://user-images.githubusercontent.com/85047449/194001099-ef56fd8a-6d81-4e94-9a17-c4515fc5adbc.png)

**Comment by emerson3** [comment]
topzera d+
